### ISSUE TITLE
make does not work out of the box on a MacOS 12.2.1

### ISSUE THREAD

**Issue by stiwari** [tvlabs/edge264#1]
./edge264_common.h:370:32: error: conflicting types for '_mm_loadu_si32'
                static always_inline __m128i _mm_loadu_si32(const uint8_t *a) {
                                             ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/emmintrin.h:1682:1: note: previous definition is here
_mm_loadu_si32(void const *__a)

**Comment by traffaillac** [comment]
Done, thanks for the report!
