### ISSUE TITLE
seg fault in edge264_test-cc

### ISSUE THREAD

**Issue by stiwari** [tvlabs/edge264#2]
This is on MacOS 12.2.1

./edge264_test-cc 
zsh: segmentation fault  ./edge264_test-cc

It's probably due to the lack of input of the conformant files. I created the directory by hand, but don't know which of the 19 files I should use to test this code. Can you please tell me which ones work? If they are CAVLC that will be great.

**Comment by traffaillac** [comment]
Can you describe exactly the contents of your conformance directory ? The program expects pairs of `.264` and `.yuv` files (c.f. image below).

<img width="752" alt="Capture d’écran 2022-03-01 à 19 09 02" src="https://user-images.githubusercontent.com/7462121/156224733-915f0b2f-216b-4193-8fa3-e53155713051.png">

It should ignore files which it cannot decode. Files must be in Annex B format. To generate a yuv file I use JM reference decoder, but something like `ffmpeg -i video.264 video.yuv` might also work. Videos from conformance bitstreams that are known to work are printed in image below. They contain both CAVLC and CABAC encodings which are fully supported, although there might be a few bugs left (conformance streams are unfortunately not exhaustive).

<img width="570" alt="Capture d’écran 2022-03-01 à 19 18 32" src="https://user-images.githubusercontent.com/7462121/156226011-99312f78-0cc3-4e4f-9085-834a28efcfaa.png">

If you find a supported stream that fails to decode properly, please send me the shortest GOP containing the error (max. 5s), in annex B format (https://apple.stackexchange.com/questions/337854/software-for-splitting-or-trimming-mp4-video-without-transcoding).
