### ISSUE TITLE
incompatible type for argument 1 of ‘_mm_cvtepu8_epi16’

### ISSUE THREAD

**Issue by chendilinn** [tvlabs/edge264#3]
Hello, I'm having trouble compiling:
![image](https://user-images.githubusercontent.com/31476226/179716052-e6e78a24-2e70-457b-9657-ff91557e9f5b.png)
gcc version is 7.5.0, this is the output of 'gcc -v'
![image](https://user-images.githubusercontent.com/31476226/179716538-53637a32-e1b4-4f44-a398-295a033e85bd.png)
This is the output for 'cat /proc/cpuinfo'
![image](https://user-images.githubusercontent.com/31476226/179725945-92ca183a-8ade-4331-8a62-af887cb285ba.png)
This is the output for 'lsb_release -a'
![image](https://user-images.githubusercontent.com/31476226/179765266-123850fb-c9be-49fe-9252-672e0303e64a.png)
I don't know what is the version of gcc that can compile normally! Thanks!

**Comment by traffaillac** [comment]
Hi @chendilinn,
Thank you for reporting this bug, while fixing it I discovered that this older version of GCC makes edge264 faster, actually even faster than clang!
Cheers,
Thibault
