### ISSUE TITLE
Make it possible to disable MVC support at build time?

### ISSUE THREAD

**Issue by jrmuizel** [tvlabs/edge264#6]
The patent situation around MVC is more complicated. It'd be nice to be able this functionality if needed.

**Comment by traffaillac** [comment]
Hi,
MPEGLA indicates that the MVC license is now included in AVC (https://www.mpegla.com/programs/mvc/), so why is it complicated ? Is it that old licenses do not retroactively allow MVC ?
Cheers,
Thibault

**Comment by jrmuizel** [comment]
I wasn't aware of that. Maybe everything is fine then.
